spring:
  application:
    name: registry-service
#  cloud:
#    config:
#        label: master # 对应的是git的分支，如果胚子中心使用的是本地存储，则该参数无用
#        #uri: http://localhost:8888 # 配置中心的具体地址
#        discovery:
#          enabled: true  # 开启config服务发现支持
#          service-id: config-service  # 指定server端的name，也就是 spring cloud config server端的spring.application.name的值
#        # git 仓库配置文件的名称 test-config-dev.properties   test-config 就是指application   dev就是指profile
#        profile: dev
#        name: test-config
eureka:
  client:
      register-with-eureka: false
      fetch-registry: false
      #serviceUrl:
        #defaultZone: http://eureka1:8001/eureka/,http://eureka2:8002/eureka/,http://eureka3:8003/eureka/
  server:
    eviction-interval-timer-in-ms: 40000  # eureka server 清理无效节点的时间间隔,默认是60000毫秒 即60秒
    enable-self-preservation: true  # 开启自我保护功能，默认为true


#  配置高可用的eureka
server:
  port: 8001
eureka:
  instance:
    hostname: eureka1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8001/eureka/




