eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka-server}  # 从spring cloud config中动态获取信息
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5 # erueka 客户端每隔5秒拉取注册信息
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 30 # 续约到期时间(默认90秒)
    lease-renewal-interval-in-seconds: 30 # 续约更新时间 (默认30秒)
spring:
  application:
    name: user-service # spring cloud 服务提供者的名称
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest

  zipkin: # zipkin 监控中心地址
    base-url: http://localhost:9411
  # 配置数据源
  datasource:
    url: jdbc:mysql:///hitao
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    config:
      label: master # 对应的是git的分支，如果配置中心使用的是本地存储，则该参数无用
      #uri: http://localhost:8888 # 配置中心的具体地址
      discovery:
        enabled: true  # 开启config服务发现支持
        service-id: config-service  # 指定server端的name，也就是 spring cloud config server端的spring.application.name的值
      # git 仓库配置文件的名称 test-config-dev.properties   test-config 就是指application   dev就是指profile
      profile: dev
      name: test-config
      refresh:
        enabled: true
  boot:
    admin:
      url: http://localhost:8094/
management:
  security:
    enabled: false #  取消安全限制

# jwt 配置
audience:
  clientId: 098f6bcd4621d373cade4e832627b4f6
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  name: hzitxx.com
  expiresSecond: 7200 # token有限期为2个小时

# 配置高可用的服务提供者
---
server:
  port: 8091  # 服务监听的端口
spring:
  profiles:  user-service1

---
server:
  port: 8092
spring:
  profiles: user-service2

---
server:
  port: 8093
spring:
  profiles: user-service3
