server:
  port: 9443
#  ssl:
#    key-store: F:/小程序/SSL/keystore.p12
#    key-store-password: 123456
#    key-store-type: PKCS12
#    key-alias: tomcat

spring:
  application:
    name: feign-service
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    feign:
      enabled: true
  cloud:
    config:
      label: master # 对应的是git的分支，如果配置中心使用的是本地存储，则该参数无用
      #uri: http://localhost:8888 # 配置中心的具体地址
      discovery:
        enabled: true  # 开启config服务发现支持
        service-id: config-service  # 指定server端的name，也就是 spring cloud config server端的spring.application.name的值
      # git 仓库配置文件的名称 test-config-dev.properties   test-config 就是指application   dev就是指profile
      profile: dev
      name: test-config


eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka-server}
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
#feign 使用apache的httpclient
feign:
  client:
    enabled: true
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
    response:
      enabled: true

# fallback 的默认超时时间为1秒
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 50000 #设置为5秒超时

ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000


