server:
  port: 9411
spring:
  application:
    name: zipkin-service
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/,http://localhost:8002/eureka/,http://localhost:8002/eureka/
