eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
      register-with-eureka: true
      fetch-registry: true
      registry-fetch-interval-seconds: 5 # erueka 客户端每隔5秒拉取注册信息
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 30 # 续约到期时间(默认90秒)
    lease-renewal-interval-in-seconds: 30 # 续约更新时间 (默认30秒)
    metadata-map:
      user:
        name: admin
        password: admin
server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/clark1230/config_resp
          username: clark1230
          password: Xyj123016
          default-label: master

      label: master


  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
    publisher-confirms: true
    publisher-returns: true

    template:
      retry:
        enabled: true
  boot:
    admin:
      client:
        url: "http://localhost:8094"
        username: admin
        password: admin
#  security:
#    user:
#      name: admin
#      password: admin

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"



#security:
#  basic:
#    enabled: false
# 取消安全限制
#management:
#  security:
#    enabled: false


#https://github.com/clark1230/config_resp
